### ISSUE TITLE
Recommened Links aren't formatted correctly

### ISSUE THREAD

**Issue by decriptor** [MicrosoftDocs/CommunityToolkit#255] opened 2023-04-29 16:13 UTC
The `<` character is incorrect:

![image](https://user-images.githubusercontent.com/49821/235312544-852752dc-a045-465d-b7ed-10ef501aae40.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68628aad-aa66-fe2d-e758-d650cabcdab7
* Version Independent ID: 68628aad-aa66-fe2d-e758-d650cabcdab7
* Content: [Introduction to the High Performance package - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/high-performance/introduction?source=docs)
* Content Source: [docs/high-performance/Introduction.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/high-performance/Introduction.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @Sergio0694
* Microsoft Alias: **joverslu**

**Comment by michael-hawker** [comment] 2023-08-25 23:21
Duplicate of #252

**Closed by michael-hawker** 2023-08-25 23:21 UTC
Labels: dotnet-communitytoolkit/prod, Pri1, dotnet
